/*jshint moz:true */
/* generated by util/MakeExchangeData.js */
const ExchangeData = {
    "EUR": [
        "kraken"
    ],
    "USD": [
        "kraken"
    ],
    "XBT": [
        "kraken"
    ]
};
